export const comunas = {
  comunas: [
    "algarrobo",
    "alhué",
    "alto biobío",
    "alto del carmen",
    "alto hospicio",
    "ancud",
    "andacollo",
    "angol",
    "antofagasta",
    "antuco",
    "arauco",
    "arica",
    "buin",
    "bulnes",
    "cabildo",
    "cabo de hornos",
    "cabrero",
    "calama",
    "calbuco",
    "caldera",
    "calera",
    "calle larga",
    "camarones",
    "camiña",
    "canela",
    "cañete",
    "carahue",
    "cartagena",
    "casablanca",
    "castro",
    "catemu",
    "cauquenes",
    "cerrillos",
    "cerro navia",
    "chaitén",
    "chanco",
    "chepica",
    "chiguayante",
    "chile chico",
    "chillán",
    "chillán viejo",
    "chimbarongo",
    "cholchol",
    "chonchi",
    "cisnes",
    "cobquecura",
    "cochamó",
    "cochrane",
    "codegua",
    "coelemu",
    "coihaique",
    "coinco",
    "colbún",
    "colchane",
    "colina",
    "collipulli",
    "coltauco",
    "combarbalá",
    "concepción",
    "conchalí",
    "constitución",
    "contulmo",
    "copiapó",
    "coquimbo",
    "coronel",
    "corral",
    "coyhaique",
    "cunco",
    "curacautín",
    "curacaví",
    "curaco de vélez",
    "curanilahue",
    "curarreheue",
    "curepto",
    "curicó",
    "dalcahue",
    "diego de almagro",
    "el bosque",
    "el carmen",
    "el monte",
    "el quisco",
    "el tabo",
    "empedrado",
    "ercilla",
    "estación central",
    "florida",
    "freire",
    "freirina",
    "fresia",
    "frutillar",
    "futaleufú",
    "galvarino",
    "general lagos",
    "gorbea",
    "graneros",
    "guaitecas",
    "hijuelas",
    "hualañé",
    "hualpén",
    "hualqui",
    "huara",
    "huasco",
    "huechuraba",
    "illapel",
    "independencia",
    "iquique",
    "isla de maipo",
    "isla de pascua",
    "juan fernández",
    "la cisterna",
    "la cruz",
    "la estrella",
    "la florida",
    "la granja",
    "la higuera",
    "la ligua",
    "la pintana",
    "la reina",
    "la serena",
    "la unión",
    "lago ranco",
    "lago verde",
    "laguna blanca",
    "laja",
    "lampa",
    "lanco",
    "las cabras",
    "las condes",
    "lautaro",
    "lebu",
    "licantén",
    "limache",
    "linares",
    "litueche",
    "llailay",
    "llanquihue",
    "lo barnechea",
    "lo espejo",
    "lo prado",
    "lolol",
    "loncoche",
    "longaví",
    "lonquimay",
    "los alamos",
    "los andes",
    "los angeles",
    "los lagos",
    "los muermos",
    "los sauces",
    "los vilos",
    "lota",
    "lumaco",
    "machalí",
    "macul",
    "mafil",
    "maipú",
    "malloa",
    "marchihue",
    "maría elena",
    "maría pinto",
    "mariquina",
    "maule",
    "maullín",
    "mejillones",
    "melipeuco",
    "melipilla",
    "molina",
    "monte patria",
    "mostazal",
    "mulchén",
    "nacimiento",
    "nancagua",
    "navidad",
    "negrete",
    "ninhue",
    "ñiquén",
    "ñuñoa",
    "olivar",
    "ollagüe",
    "olmue",
    "osorno",
    "ovalle",
    "padre hurtado",
    "padre las casas",
    "paihuano",
    "paillaco",
    "paine",
    "palena",
    "palmilla",
    "panguipulli",
    "panquehue",
    "papudo",
    "paredones",
    "parral",
    "pedro aguirre cerda",
    "pelarco",
    "pelluhue",
    "peralillo",
    "peñaflor",
    "peñalolén",
    "perquenco",
    "petorca",
    "peumo",
    "pica",
    "pichidegua",
    "pichilemu",
    "pinto",
    "pirque",
    "piteo",
    "placilla",
    "pucón",
    "puente alto",
    "puerto montt",
    "puerto octay",
    "puerto varas",
    "pumanque",
    "punta arenas",
    "punta lavapié",
    "punitaqui",
    "puren",
    "purranque",
    "puyehue",
    "queilén",
    "quilaco",
    "quilicura",
    "quilleco",
    "quillón",
    "quillota",
    "quilpué",
    "quilaco",
    "quinchao",
    "quinquihue",
    "quinta de tilcoco",
    "quinta normal",
    "quintero",
    "quirihue",
    "rancagua",
    "ránquil",
    "rauco",
    "recoleta",
    "renaico",
    "renca",
    "rengo",
    "requinoa",
    "retiro",
    "río bueno",
    "río claro",
    "río hurtado",
    "río ibáñez",
    "río negro",
    "río verde",
    "romeral",
    "saavedra",
    "sagrada familia",
    "salamanca",
    "san antonio",
    "san bernardo",
    "san carlos",
    "san clemente",
    "san esteban",
    "san fabián",
    "san felipe",
    "san fernando",
    "san gregorio",
    "san ignacio",
    "san javier",
    "san joaquín",
    "san josé de maipo",
    "san juan de la costa",
    "san miguel",
    "san nicolás",
    "san pablo",
    "san pedro",
    "san pedro de atacama",
    "san pedro de la paz",
    "san rafael",
    "san ramón",
    "san rosendo",
    "santa bárbara",
    "santa cruz",
    "santa juana",
    "santa maría",
    "santiago",
    "santo domingo",
    "sierra gorda",
    "talagante",
    "talcahuano",
    "talcahuano viejo",
    "taltal",
    "temuco",
    "tepual",
    "teodoro schmidt",
    "tierra amarilla",
    "tiltil",
    "tocopilla",
    "tolten",
    "tomé",
    "torres del paine",
    "tortel",
    "trauco",
    "trehuaco",
    "tucapel",
    "valdivia",
    "vicuña",
    "victoria",
    "vilcún",
    "villa alegre",
    "villa alemana",
    "villarrica",
    "viña del mar",
    "vitacura",
    "yumbel",
    "yungay",
    "zapallar",
  ],
};
